language: java
jdk:
  - openjdk17

branches:
  except:
    - main
		- develop

branches:
  only:
    - document/travis

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r backend_e-weather # 모든 파일을 eweather-backend로 압축
  - mkdir -p deploy
  - mv backend_e-weather.zip deploy/backend_e-weather.zip

deploy:
  - provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: eweather-bucket
  region: ap-northeast-2
  skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: document/travis

notifications:
  email:
    recipients:
      - ewha.weather@gmail.com
